data_store:
  hf_dataset_name: philschmid/emotion
  hf_dataset_split: train
  local_path: data/twitter-emotion
  s3_prefix: twitter-emotion
tokenizer_store:
  local_path: tokenizer.model
  s3_prefix: bert-base-uncased/tokenizer
model_store:
  hf_model_name: bert-base-uncased
  local_weights_path: model
  local_checkpoints_path: model/checkpoints
  s3_prefix: bert-base-uncased/model
  s3_checkpoints_key: checkpoints
  s3_experiments_key: experiments
  s3_neuron_compiler_cache_key: neuron-compiler-cache
training:
  bf16: true
  learning_rate: 5.0e-05
  per_device_train_batch_size: 2
  epochs: 1
  logging_steps: 10
